import type { EditField } from "@/components/generic-edit-dialog";
import { CURRENCIES } from "@/lib/exchange";

const ccy = (): EditField["options"] => CURRENCIES.map((c) => ({ value: c, label: c }));

const SETTLEMENT: EditField["options"] = [
  { value: "draft", label: "Draft" },
  { value: "pending_docs", label: "Pending docs" },
  { value: "pending_delivery", label: "Pending delivery" },
  { value: "completed", label: "Completed" },
  { value: "cancelled", label: "Cancelled" },
];

const DEAL_STATUS: EditField["options"] = [
  { value: "open", label: "Open" },
  { value: "waiting_payment", label: "Waiting for payment" },
  { value: "partially_paid", label: "Partially paid" },
  { value: "waiting_receipt", label: "Waiting for receipt" },
  { value: "ready_to_close", label: "Ready to close" },
  { value: "closed", label: "Closed" },
  { value: "cancelled", label: "Cancelled" },
];

const OWNER: EditField["options"] = [
  { value: "shared", label: "Shared" },
  { value: "milad", label: "Milad" },
  { value: "ali", label: "Ali" },
  { value: "other", label: "Other" },
];

const BROUGHT_BY: EditField["options"] = [
  { value: "milad", label: "Milad" },
  { value: "ali", label: "Ali" },
  { value: "customer", label: "Customer" },
  { value: "other", label: "Other" },
];

const ACCOUNT_TYPES: EditField["options"] = [
  { value: "cash", label: "Cash" },
  { value: "bank", label: "Bank" },
  { value: "person_holding", label: "Cash with Person" },
  { value: "customer_wallet", label: "Customer wallet" },
  { value: "other", label: "Other" },
];

const TRADE_STATUS: EditField["options"] = [
  { value: "draft", label: "Draft" },
  { value: "open", label: "Open" },
  { value: "in_progress", label: "In progress" },
  { value: "partially_closed", label: "Partially closed" },
  { value: "profit_pending", label: "Profit pending" },
  { value: "awaiting_profit", label: "Awaiting profit" },
  { value: "awaiting_docs", label: "Awaiting docs" },
  { value: "completed", label: "Completed" },
  { value: "loss", label: "Loss" },
  { value: "cancelled", label: "Cancelled" },
];

export const EDIT_FIELDS: Record<string, EditField[]> = {
  accounts: [
    { key: "name", label: "Account name" },
    { key: "account_type", label: "Account type", type: "select", options: ACCOUNT_TYPES },
    { key: "currency", label: "Currency", type: "select", options: ccy() },
    { key: "owner", label: "Owner", type: "select", options: OWNER },
    { key: "bank_name", label: "Bank name" },
    { key: "holder_name", label: "Account holder" },
    { key: "account_number", label: "Account number" },
    { key: "iban", label: "IBAN" },
    { key: "card_number", label: "Card number" },
    { key: "opening_balance", label: "Opening balance", type: "number", step: "0.0001" },
    { key: "low_balance_threshold", label: "Low-balance threshold", type: "number", step: "0.01" },
    { key: "holder_person_name", label: "Person name (Cash with…)" },
    { key: "is_active", label: "Active", type: "boolean" },
    { key: "notes", label: "Notes", type: "textarea" },
  ],
  customers: [
    { key: "name", label: "Name" },
    { key: "phone", label: "Phone" },
    { key: "notes", label: "Notes", type: "textarea" },
  ],
  brought_in_money: [
    { key: "entry_date", label: "Date", type: "date" },
    { key: "brought_by", label: "Brought by", type: "select", options: BROUGHT_BY },
    { key: "source_name", label: "Customer / source name" },
    { key: "currency", label: "Original currency", type: "select", options: ccy() },
    { key: "amount", label: "Original amount", type: "number", step: "0.0001" },
    { key: "deposit_account_id", label: "Destination account", type: "account", filterCurrency: "currency" },
    { key: "convert_enabled", label: "Converted?", type: "boolean" },
    { key: "converted_currency", label: "Converted currency", type: "select", options: ccy() },
    { key: "converted_amount", label: "Converted amount", type: "number", step: "0.0001" },
    { key: "conversion_rate", label: "Conversion rate", type: "number", step: "0.00000001" },
    { key: "final_deposit_account_id", label: "Final destination account", type: "account", optional: true, filterCurrency: "converted_currency" },
    { key: "conversion_fee_amount", label: "Conversion fee", type: "number", step: "0.0001" },
    { key: "conversion_fee_currency", label: "Fee currency", type: "select", options: ccy() },
    { key: "sender_bank_name", label: "Sender bank" },
    { key: "sender_account_name", label: "Sender account name" },
    { key: "sender_account_number", label: "Sender account #" },
    { key: "source_location_label", label: "Source label" },
    { key: "notes", label: "Notes", type: "textarea" },
  ],
  buy_transactions: [
    { key: "entry_date", label: "Date", type: "date" },
    { key: "bought_currency", label: "Bought currency", type: "select", options: ccy() },
    { key: "bought_amount", label: "Bought amount", type: "number", step: "0.0001" },
    { key: "buy_rate", label: "Buy rate", type: "number", step: "0.00000001" },
    { key: "paid_currency", label: "Paid currency", type: "select", options: ccy() },
    { key: "paid_amount", label: "Paid amount", type: "number", step: "0.0001" },
    { key: "paid_from_account_id", label: "Paid from account", type: "account", filterCurrency: "paid_currency" },
    { key: "received_into_account_id", label: "Received into account", type: "account", filterCurrency: "bought_currency" },
    { key: "customer_id", label: "Customer / counterparty", type: "customer" },
    { key: "counterparty", label: "Counterparty (free text)" },
    { key: "trade_cycle_id", label: "Linked trade cycle", type: "trade_cycle", optional: true },
    { key: "settlement_status", label: "Settlement status", type: "select", options: SETTLEMENT },
    { key: "notes", label: "Notes", type: "textarea" },
  ],
  sell_transactions: [
    { key: "entry_date", label: "Date", type: "date" },
    { key: "customer_id", label: "Customer", type: "customer" },
    { key: "customer_name", label: "Customer name (free text)" },
    { key: "customer_phone", label: "Customer phone" },
    { key: "customer_account", label: "Customer account ref" },
    { key: "sold_currency", label: "Currency sold", type: "select", options: ccy() },
    { key: "sold_amount", label: "Amount sold", type: "number", step: "0.0001" },
    { key: "sell_rate", label: "Sell rate", type: "number", step: "0.00000001" },
    { key: "received_currency", label: "Received currency", type: "select", options: ccy() },
    { key: "received_amount", label: "Received amount", type: "number", step: "0.0001" },
    { key: "sold_from_account_id", label: "Sold from account", type: "account", filterCurrency: "sold_currency" },
    { key: "received_into_account_id", label: "Received into account", type: "account", optional: true, filterCurrency: "received_currency" },
    { key: "deal_status", label: "Deal status", type: "select", options: DEAL_STATUS },
    { key: "settlement_status", label: "Settlement status", type: "select", options: SETTLEMENT },
    { key: "expected_payment_date", label: "Expected payment date", type: "date" },
    { key: "milad_share_pct", label: "Milad share %", type: "number", step: "0.01" },
    { key: "ali_share_pct", label: "Ali share %", type: "number", step: "0.01" },
    { key: "trade_cycle_id", label: "Linked trade cycle", type: "trade_cycle", optional: true },
    { key: "notes", label: "Notes", type: "textarea" },
  ],
  expenses: [
    { key: "entry_date", label: "Date", type: "date" },
    { key: "amount", label: "Amount", type: "number", step: "0.0001" },
    { key: "currency", label: "Currency", type: "select", options: ccy() },
    { key: "paid_from_account_id", label: "Paid from", type: "account", filterCurrency: "currency" },
    { key: "category", label: "Category" },
    { key: "paid_by", label: "Paid by", type: "select", options: BROUGHT_BY },
    { key: "reduces_profit", label: "Reduces profit", type: "boolean" },
    { key: "reduce_cycle_profit", label: "Reduce cycle profit", type: "boolean" },
    { key: "trade_cycle_id", label: "Linked trade cycle", type: "trade_cycle", optional: true },
    { key: "settlement_status", label: "Settlement status", type: "select", options: SETTLEMENT },
    { key: "notes", label: "Notes / description", type: "textarea" },
  ],
  transfers: [
    { key: "entry_date", label: "Date", type: "date" },
    { key: "currency", label: "Currency", type: "select", options: ccy() },
    { key: "amount", label: "Amount", type: "number", step: "0.0001" },
    { key: "from_account_id", label: "From account", type: "account", filterCurrency: "currency" },
    { key: "to_account_id", label: "To account", type: "account", filterCurrency: "currency" },
    { key: "reason", label: "Reason" },
    { key: "requested_by", label: "Requested by", type: "select", options: BROUGHT_BY },
    { key: "settlement_status", label: "Settlement status", type: "select", options: SETTLEMENT },
    { key: "notes", label: "Notes", type: "textarea" },
  ],
  customer_deposits: [
    { key: "entry_date", label: "Date", type: "date" },
    { key: "customer_id", label: "Customer", type: "customer" },
    { key: "currency", label: "Currency", type: "select", options: ccy() },
    { key: "amount", label: "Amount", type: "number", step: "0.0001" },
    { key: "deposit_account_id", label: "Deposit account", type: "account", filterCurrency: "currency" },
    { key: "wallet_account_id", label: "Wallet account", type: "account", filterCurrency: "currency" },
    { key: "settlement_status", label: "Settlement status", type: "select", options: SETTLEMENT },
    { key: "notes", label: "Notes", type: "textarea" },
  ],
  trade_cycles: [
    { key: "entry_date", label: "Date", type: "date" },
    { key: "code", label: "Code" },
    { key: "title", label: "Title" },
    { key: "customer_id", label: "Customer", type: "customer" },
    { key: "base_currency", label: "Base currency", type: "select", options: ccy() },
    { key: "quote_currency", label: "Quote currency", type: "select", options: ccy() },
    { key: "initial_currency", label: "Initial currency", type: "select", options: ccy() },
    { key: "initial_amount", label: "Initial amount", type: "number", step: "0.0001" },
    { key: "initial_account_id", label: "Initial account", type: "account", optional: true, filterCurrency: "initial_currency" },
    { key: "intermediate_currency", label: "Intermediate currency", type: "select", options: ccy() },
    { key: "intermediate_account_id", label: "Intermediate account", type: "account", optional: true, filterCurrency: "intermediate_currency" },
    { key: "final_currency", label: "Final currency", type: "select", options: ccy() },
    { key: "final_account_id", label: "Final account", type: "account", optional: true, filterCurrency: "final_currency" },
    { key: "milad_share_pct", label: "Milad share %", type: "number", step: "0.001" },
    { key: "ali_share_pct", label: "Ali share %", type: "number", step: "0.001" },
    { key: "status", label: "Status", type: "select", options: TRADE_STATUS },
    { key: "notes", label: "Notes", type: "textarea" },
  ],
  sell_payments: [
    { key: "entry_date", label: "Date", type: "date" },
    { key: "currency", label: "Currency", type: "select", options: ccy() },
    { key: "amount", label: "Amount", type: "number", step: "0.0001" },
    { key: "received_into_account_id", label: "Received into account", type: "account", filterCurrency: "currency" },
    { key: "notes", label: "Notes", type: "textarea" },
  ],
  inventory_lots: [
    { key: "entry_date", label: "Entry date", type: "date" },
    { key: "currency", label: "Currency", type: "select", options: ccy() },
    { key: "account_id", label: "Account", type: "account", optional: true, filterCurrency: "currency" },
    { key: "original_amount", label: "Original amount", type: "number", step: "0.0001" },
    { key: "remaining_amount", label: "Remaining amount", type: "number", step: "0.0001" },
    { key: "cost_basis_rate", label: "Cost basis rate", type: "number", step: "0.00000001" },
    { key: "cost_basis_currency", label: "Cost basis currency", type: "select", options: ccy() },
    { key: "source_description", label: "Source description", type: "textarea" },
  ],
  payment_orders: [
    { key: "entry_date", label: "Date", type: "date" },
    { key: "customer_id", label: "Customer", type: "customer" },
    { key: "currency", label: "Currency", type: "select", options: ccy() },
    { key: "amount", label: "Amount", type: "number", step: "0.0001" },
    { key: "source_wallet_account_id", label: "Source wallet", type: "account", filterCurrency: "currency" },
    { key: "paid_from_account_id", label: "Paid from account", type: "account", optional: true, filterCurrency: "currency" },
    { key: "service_charge_amount", label: "Service charge amount", type: "number", step: "0.0001" },
    { key: "service_charge_currency", label: "Service charge currency", type: "select", options: ccy() },
    { key: "settlement_status", label: "Settlement status", type: "select", options: SETTLEMENT },
    { key: "notes", label: "Notes", type: "textarea" },
  ],
};