/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWalletsRouteImport } from './routes/_authenticated/wallets'
import { Route as AuthenticatedTrustRouteImport } from './routes/_authenticated/trust'
import { Route as AuthenticatedTransfersRouteImport } from './routes/_authenticated/transfers'
import { Route as AuthenticatedTradesRouteImport } from './routes/_authenticated/trades'
import { Route as AuthenticatedStatementsRouteImport } from './routes/_authenticated/statements'
import { Route as AuthenticatedSellRouteImport } from './routes/_authenticated/sell'
import { Route as AuthenticatedRolesRouteImport } from './routes/_authenticated/roles'
import { Route as AuthenticatedQuickSellRouteImport } from './routes/_authenticated/quick-sell'
import { Route as AuthenticatedPendingSettlementsRouteImport } from './routes/_authenticated/pending-settlements'
import { Route as AuthenticatedPaymentOrdersRouteImport } from './routes/_authenticated/payment-orders'
import { Route as AuthenticatedInventoryRouteImport } from './routes/_authenticated/inventory'
import { Route as AuthenticatedHeldByPersonRouteImport } from './routes/_authenticated/held-by-person'
import { Route as AuthenticatedExpensesRouteImport } from './routes/_authenticated/expenses'
import { Route as AuthenticatedDepositsRouteImport } from './routes/_authenticated/deposits'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDailyClosingRouteImport } from './routes/_authenticated/daily-closing'
import { Route as AuthenticatedCustomersRouteImport } from './routes/_authenticated/customers'
import { Route as AuthenticatedCommandCenterRouteImport } from './routes/_authenticated/command-center'
import { Route as AuthenticatedBuyRouteImport } from './routes/_authenticated/buy'
import { Route as AuthenticatedBroughtInRouteImport } from './routes/_authenticated/brought-in'
import { Route as AuthenticatedAuditRouteImport } from './routes/_authenticated/audit'
import { Route as AuthenticatedAliInvestorRouteImport } from './routes/_authenticated/ali-investor'
import { Route as AuthenticatedAccountsRouteImport } from './routes/_authenticated/accounts'
import { Route as AuthenticatedTradesIdRouteImport } from './routes/_authenticated/trades.$id'
import { Route as AuthenticatedDepositsNewRouteImport } from './routes/_authenticated/deposits.new'
import { Route as AuthenticatedBroughtInNewRouteImport } from './routes/_authenticated/brought-in.new'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWalletsRoute = AuthenticatedWalletsRouteImport.update({
  id: '/wallets',
  path: '/wallets',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTrustRoute = AuthenticatedTrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTransfersRoute = AuthenticatedTransfersRouteImport.update({
  id: '/transfers',
  path: '/transfers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTradesRoute = AuthenticatedTradesRouteImport.update({
  id: '/trades',
  path: '/trades',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStatementsRoute = AuthenticatedStatementsRouteImport.update({
  id: '/statements',
  path: '/statements',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSellRoute = AuthenticatedSellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRolesRoute = AuthenticatedRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQuickSellRoute = AuthenticatedQuickSellRouteImport.update({
  id: '/quick-sell',
  path: '/quick-sell',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPendingSettlementsRoute =
  AuthenticatedPendingSettlementsRouteImport.update({
    id: '/pending-settlements',
    path: '/pending-settlements',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPaymentOrdersRoute =
  AuthenticatedPaymentOrdersRouteImport.update({
    id: '/payment-orders',
    path: '/payment-orders',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInventoryRoute = AuthenticatedInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHeldByPersonRoute =
  AuthenticatedHeldByPersonRouteImport.update({
    id: '/held-by-person',
    path: '/held-by-person',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExpensesRoute = AuthenticatedExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDepositsRoute = AuthenticatedDepositsRouteImport.update({
  id: '/deposits',
  path: '/deposits',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDailyClosingRoute =
  AuthenticatedDailyClosingRouteImport.update({
    id: '/daily-closing',
    path: '/daily-closing',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCustomersRoute = AuthenticatedCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCommandCenterRoute =
  AuthenticatedCommandCenterRouteImport.update({
    id: '/command-center',
    path: '/command-center',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBuyRoute = AuthenticatedBuyRouteImport.update({
  id: '/buy',
  path: '/buy',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBroughtInRoute = AuthenticatedBroughtInRouteImport.update({
  id: '/brought-in',
  path: '/brought-in',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditRoute = AuthenticatedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAliInvestorRoute =
  AuthenticatedAliInvestorRouteImport.update({
    id: '/ali-investor',
    path: '/ali-investor',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccountsRoute = AuthenticatedAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTradesIdRoute = AuthenticatedTradesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedTradesRoute,
} as any)
const AuthenticatedDepositsNewRoute =
  AuthenticatedDepositsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedDepositsRoute,
  } as any)
const AuthenticatedBroughtInNewRoute =
  AuthenticatedBroughtInNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedBroughtInRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/accounts': typeof AuthenticatedAccountsRoute
  '/ali-investor': typeof AuthenticatedAliInvestorRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/brought-in': typeof AuthenticatedBroughtInRouteWithChildren
  '/buy': typeof AuthenticatedBuyRoute
  '/command-center': typeof AuthenticatedCommandCenterRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/daily-closing': typeof AuthenticatedDailyClosingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/deposits': typeof AuthenticatedDepositsRouteWithChildren
  '/expenses': typeof AuthenticatedExpensesRoute
  '/held-by-person': typeof AuthenticatedHeldByPersonRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/payment-orders': typeof AuthenticatedPaymentOrdersRoute
  '/pending-settlements': typeof AuthenticatedPendingSettlementsRoute
  '/quick-sell': typeof AuthenticatedQuickSellRoute
  '/roles': typeof AuthenticatedRolesRoute
  '/sell': typeof AuthenticatedSellRoute
  '/statements': typeof AuthenticatedStatementsRoute
  '/trades': typeof AuthenticatedTradesRouteWithChildren
  '/transfers': typeof AuthenticatedTransfersRoute
  '/trust': typeof AuthenticatedTrustRoute
  '/wallets': typeof AuthenticatedWalletsRoute
  '/brought-in/new': typeof AuthenticatedBroughtInNewRoute
  '/deposits/new': typeof AuthenticatedDepositsNewRoute
  '/trades/$id': typeof AuthenticatedTradesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/accounts': typeof AuthenticatedAccountsRoute
  '/ali-investor': typeof AuthenticatedAliInvestorRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/brought-in': typeof AuthenticatedBroughtInRouteWithChildren
  '/buy': typeof AuthenticatedBuyRoute
  '/command-center': typeof AuthenticatedCommandCenterRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/daily-closing': typeof AuthenticatedDailyClosingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/deposits': typeof AuthenticatedDepositsRouteWithChildren
  '/expenses': typeof AuthenticatedExpensesRoute
  '/held-by-person': typeof AuthenticatedHeldByPersonRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/payment-orders': typeof AuthenticatedPaymentOrdersRoute
  '/pending-settlements': typeof AuthenticatedPendingSettlementsRoute
  '/quick-sell': typeof AuthenticatedQuickSellRoute
  '/roles': typeof AuthenticatedRolesRoute
  '/sell': typeof AuthenticatedSellRoute
  '/statements': typeof AuthenticatedStatementsRoute
  '/trades': typeof AuthenticatedTradesRouteWithChildren
  '/transfers': typeof AuthenticatedTransfersRoute
  '/trust': typeof AuthenticatedTrustRoute
  '/wallets': typeof AuthenticatedWalletsRoute
  '/brought-in/new': typeof AuthenticatedBroughtInNewRoute
  '/deposits/new': typeof AuthenticatedDepositsNewRoute
  '/trades/$id': typeof AuthenticatedTradesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/accounts': typeof AuthenticatedAccountsRoute
  '/_authenticated/ali-investor': typeof AuthenticatedAliInvestorRoute
  '/_authenticated/audit': typeof AuthenticatedAuditRoute
  '/_authenticated/brought-in': typeof AuthenticatedBroughtInRouteWithChildren
  '/_authenticated/buy': typeof AuthenticatedBuyRoute
  '/_authenticated/command-center': typeof AuthenticatedCommandCenterRoute
  '/_authenticated/customers': typeof AuthenticatedCustomersRoute
  '/_authenticated/daily-closing': typeof AuthenticatedDailyClosingRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/deposits': typeof AuthenticatedDepositsRouteWithChildren
  '/_authenticated/expenses': typeof AuthenticatedExpensesRoute
  '/_authenticated/held-by-person': typeof AuthenticatedHeldByPersonRoute
  '/_authenticated/inventory': typeof AuthenticatedInventoryRoute
  '/_authenticated/payment-orders': typeof AuthenticatedPaymentOrdersRoute
  '/_authenticated/pending-settlements': typeof AuthenticatedPendingSettlementsRoute
  '/_authenticated/quick-sell': typeof AuthenticatedQuickSellRoute
  '/_authenticated/roles': typeof AuthenticatedRolesRoute
  '/_authenticated/sell': typeof AuthenticatedSellRoute
  '/_authenticated/statements': typeof AuthenticatedStatementsRoute
  '/_authenticated/trades': typeof AuthenticatedTradesRouteWithChildren
  '/_authenticated/transfers': typeof AuthenticatedTransfersRoute
  '/_authenticated/trust': typeof AuthenticatedTrustRoute
  '/_authenticated/wallets': typeof AuthenticatedWalletsRoute
  '/_authenticated/brought-in/new': typeof AuthenticatedBroughtInNewRoute
  '/_authenticated/deposits/new': typeof AuthenticatedDepositsNewRoute
  '/_authenticated/trades/$id': typeof AuthenticatedTradesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/accounts'
    | '/ali-investor'
    | '/audit'
    | '/brought-in'
    | '/buy'
    | '/command-center'
    | '/customers'
    | '/daily-closing'
    | '/dashboard'
    | '/deposits'
    | '/expenses'
    | '/held-by-person'
    | '/inventory'
    | '/payment-orders'
    | '/pending-settlements'
    | '/quick-sell'
    | '/roles'
    | '/sell'
    | '/statements'
    | '/trades'
    | '/transfers'
    | '/trust'
    | '/wallets'
    | '/brought-in/new'
    | '/deposits/new'
    | '/trades/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/accounts'
    | '/ali-investor'
    | '/audit'
    | '/brought-in'
    | '/buy'
    | '/command-center'
    | '/customers'
    | '/daily-closing'
    | '/dashboard'
    | '/deposits'
    | '/expenses'
    | '/held-by-person'
    | '/inventory'
    | '/payment-orders'
    | '/pending-settlements'
    | '/quick-sell'
    | '/roles'
    | '/sell'
    | '/statements'
    | '/trades'
    | '/transfers'
    | '/trust'
    | '/wallets'
    | '/brought-in/new'
    | '/deposits/new'
    | '/trades/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/accounts'
    | '/_authenticated/ali-investor'
    | '/_authenticated/audit'
    | '/_authenticated/brought-in'
    | '/_authenticated/buy'
    | '/_authenticated/command-center'
    | '/_authenticated/customers'
    | '/_authenticated/daily-closing'
    | '/_authenticated/dashboard'
    | '/_authenticated/deposits'
    | '/_authenticated/expenses'
    | '/_authenticated/held-by-person'
    | '/_authenticated/inventory'
    | '/_authenticated/payment-orders'
    | '/_authenticated/pending-settlements'
    | '/_authenticated/quick-sell'
    | '/_authenticated/roles'
    | '/_authenticated/sell'
    | '/_authenticated/statements'
    | '/_authenticated/trades'
    | '/_authenticated/transfers'
    | '/_authenticated/trust'
    | '/_authenticated/wallets'
    | '/_authenticated/brought-in/new'
    | '/_authenticated/deposits/new'
    | '/_authenticated/trades/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/wallets': {
      id: '/_authenticated/wallets'
      path: '/wallets'
      fullPath: '/wallets'
      preLoaderRoute: typeof AuthenticatedWalletsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/trust': {
      id: '/_authenticated/trust'
      path: '/trust'
      fullPath: '/trust'
      preLoaderRoute: typeof AuthenticatedTrustRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transfers': {
      id: '/_authenticated/transfers'
      path: '/transfers'
      fullPath: '/transfers'
      preLoaderRoute: typeof AuthenticatedTransfersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/trades': {
      id: '/_authenticated/trades'
      path: '/trades'
      fullPath: '/trades'
      preLoaderRoute: typeof AuthenticatedTradesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/statements': {
      id: '/_authenticated/statements'
      path: '/statements'
      fullPath: '/statements'
      preLoaderRoute: typeof AuthenticatedStatementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sell': {
      id: '/_authenticated/sell'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof AuthenticatedSellRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/roles': {
      id: '/_authenticated/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof AuthenticatedRolesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quick-sell': {
      id: '/_authenticated/quick-sell'
      path: '/quick-sell'
      fullPath: '/quick-sell'
      preLoaderRoute: typeof AuthenticatedQuickSellRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pending-settlements': {
      id: '/_authenticated/pending-settlements'
      path: '/pending-settlements'
      fullPath: '/pending-settlements'
      preLoaderRoute: typeof AuthenticatedPendingSettlementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payment-orders': {
      id: '/_authenticated/payment-orders'
      path: '/payment-orders'
      fullPath: '/payment-orders'
      preLoaderRoute: typeof AuthenticatedPaymentOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory': {
      id: '/_authenticated/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedInventoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/held-by-person': {
      id: '/_authenticated/held-by-person'
      path: '/held-by-person'
      fullPath: '/held-by-person'
      preLoaderRoute: typeof AuthenticatedHeldByPersonRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/expenses': {
      id: '/_authenticated/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AuthenticatedExpensesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/deposits': {
      id: '/_authenticated/deposits'
      path: '/deposits'
      fullPath: '/deposits'
      preLoaderRoute: typeof AuthenticatedDepositsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/daily-closing': {
      id: '/_authenticated/daily-closing'
      path: '/daily-closing'
      fullPath: '/daily-closing'
      preLoaderRoute: typeof AuthenticatedDailyClosingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers': {
      id: '/_authenticated/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedCustomersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/command-center': {
      id: '/_authenticated/command-center'
      path: '/command-center'
      fullPath: '/command-center'
      preLoaderRoute: typeof AuthenticatedCommandCenterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/buy': {
      id: '/_authenticated/buy'
      path: '/buy'
      fullPath: '/buy'
      preLoaderRoute: typeof AuthenticatedBuyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/brought-in': {
      id: '/_authenticated/brought-in'
      path: '/brought-in'
      fullPath: '/brought-in'
      preLoaderRoute: typeof AuthenticatedBroughtInRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit': {
      id: '/_authenticated/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ali-investor': {
      id: '/_authenticated/ali-investor'
      path: '/ali-investor'
      fullPath: '/ali-investor'
      preLoaderRoute: typeof AuthenticatedAliInvestorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/accounts': {
      id: '/_authenticated/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AuthenticatedAccountsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/trades/$id': {
      id: '/_authenticated/trades/$id'
      path: '/$id'
      fullPath: '/trades/$id'
      preLoaderRoute: typeof AuthenticatedTradesIdRouteImport
      parentRoute: typeof AuthenticatedTradesRoute
    }
    '/_authenticated/deposits/new': {
      id: '/_authenticated/deposits/new'
      path: '/new'
      fullPath: '/deposits/new'
      preLoaderRoute: typeof AuthenticatedDepositsNewRouteImport
      parentRoute: typeof AuthenticatedDepositsRoute
    }
    '/_authenticated/brought-in/new': {
      id: '/_authenticated/brought-in/new'
      path: '/new'
      fullPath: '/brought-in/new'
      preLoaderRoute: typeof AuthenticatedBroughtInNewRouteImport
      parentRoute: typeof AuthenticatedBroughtInRoute
    }
  }
}

interface AuthenticatedBroughtInRouteChildren {
  AuthenticatedBroughtInNewRoute: typeof AuthenticatedBroughtInNewRoute
}

const AuthenticatedBroughtInRouteChildren: AuthenticatedBroughtInRouteChildren =
  {
    AuthenticatedBroughtInNewRoute: AuthenticatedBroughtInNewRoute,
  }

const AuthenticatedBroughtInRouteWithChildren =
  AuthenticatedBroughtInRoute._addFileChildren(
    AuthenticatedBroughtInRouteChildren,
  )

interface AuthenticatedDepositsRouteChildren {
  AuthenticatedDepositsNewRoute: typeof AuthenticatedDepositsNewRoute
}

const AuthenticatedDepositsRouteChildren: AuthenticatedDepositsRouteChildren = {
  AuthenticatedDepositsNewRoute: AuthenticatedDepositsNewRoute,
}

const AuthenticatedDepositsRouteWithChildren =
  AuthenticatedDepositsRoute._addFileChildren(
    AuthenticatedDepositsRouteChildren,
  )

interface AuthenticatedTradesRouteChildren {
  AuthenticatedTradesIdRoute: typeof AuthenticatedTradesIdRoute
}

const AuthenticatedTradesRouteChildren: AuthenticatedTradesRouteChildren = {
  AuthenticatedTradesIdRoute: AuthenticatedTradesIdRoute,
}

const AuthenticatedTradesRouteWithChildren =
  AuthenticatedTradesRoute._addFileChildren(AuthenticatedTradesRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountsRoute: typeof AuthenticatedAccountsRoute
  AuthenticatedAliInvestorRoute: typeof AuthenticatedAliInvestorRoute
  AuthenticatedAuditRoute: typeof AuthenticatedAuditRoute
  AuthenticatedBroughtInRoute: typeof AuthenticatedBroughtInRouteWithChildren
  AuthenticatedBuyRoute: typeof AuthenticatedBuyRoute
  AuthenticatedCommandCenterRoute: typeof AuthenticatedCommandCenterRoute
  AuthenticatedCustomersRoute: typeof AuthenticatedCustomersRoute
  AuthenticatedDailyClosingRoute: typeof AuthenticatedDailyClosingRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDepositsRoute: typeof AuthenticatedDepositsRouteWithChildren
  AuthenticatedExpensesRoute: typeof AuthenticatedExpensesRoute
  AuthenticatedHeldByPersonRoute: typeof AuthenticatedHeldByPersonRoute
  AuthenticatedInventoryRoute: typeof AuthenticatedInventoryRoute
  AuthenticatedPaymentOrdersRoute: typeof AuthenticatedPaymentOrdersRoute
  AuthenticatedPendingSettlementsRoute: typeof AuthenticatedPendingSettlementsRoute
  AuthenticatedQuickSellRoute: typeof AuthenticatedQuickSellRoute
  AuthenticatedRolesRoute: typeof AuthenticatedRolesRoute
  AuthenticatedSellRoute: typeof AuthenticatedSellRoute
  AuthenticatedStatementsRoute: typeof AuthenticatedStatementsRoute
  AuthenticatedTradesRoute: typeof AuthenticatedTradesRouteWithChildren
  AuthenticatedTransfersRoute: typeof AuthenticatedTransfersRoute
  AuthenticatedTrustRoute: typeof AuthenticatedTrustRoute
  AuthenticatedWalletsRoute: typeof AuthenticatedWalletsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountsRoute: AuthenticatedAccountsRoute,
  AuthenticatedAliInvestorRoute: AuthenticatedAliInvestorRoute,
  AuthenticatedAuditRoute: AuthenticatedAuditRoute,
  AuthenticatedBroughtInRoute: AuthenticatedBroughtInRouteWithChildren,
  AuthenticatedBuyRoute: AuthenticatedBuyRoute,
  AuthenticatedCommandCenterRoute: AuthenticatedCommandCenterRoute,
  AuthenticatedCustomersRoute: AuthenticatedCustomersRoute,
  AuthenticatedDailyClosingRoute: AuthenticatedDailyClosingRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDepositsRoute: AuthenticatedDepositsRouteWithChildren,
  AuthenticatedExpensesRoute: AuthenticatedExpensesRoute,
  AuthenticatedHeldByPersonRoute: AuthenticatedHeldByPersonRoute,
  AuthenticatedInventoryRoute: AuthenticatedInventoryRoute,
  AuthenticatedPaymentOrdersRoute: AuthenticatedPaymentOrdersRoute,
  AuthenticatedPendingSettlementsRoute: AuthenticatedPendingSettlementsRoute,
  AuthenticatedQuickSellRoute: AuthenticatedQuickSellRoute,
  AuthenticatedRolesRoute: AuthenticatedRolesRoute,
  AuthenticatedSellRoute: AuthenticatedSellRoute,
  AuthenticatedStatementsRoute: AuthenticatedStatementsRoute,
  AuthenticatedTradesRoute: AuthenticatedTradesRouteWithChildren,
  AuthenticatedTransfersRoute: AuthenticatedTransfersRoute,
  AuthenticatedTrustRoute: AuthenticatedTrustRoute,
  AuthenticatedWalletsRoute: AuthenticatedWalletsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
