/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWalletsRouteImport } from './routes/_authenticated/wallets'
import { Route as AuthenticatedTrustRouteImport } from './routes/_authenticated/trust'
import { Route as AuthenticatedTransfersRouteImport } from './routes/_authenticated/transfers'
import { Route as AuthenticatedTradesRouteImport } from './routes/_authenticated/trades'
import { Route as AuthenticatedStatementsRouteImport } from './routes/_authenticated/statements'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSellRouteImport } from './routes/_authenticated/sell'
import { Route as AuthenticatedRolesRouteImport } from './routes/_authenticated/roles'
import { Route as AuthenticatedQuickSellRouteImport } from './routes/_authenticated/quick-sell'
import { Route as AuthenticatedPendingSettlementsRouteImport } from './routes/_authenticated/pending-settlements'
import { Route as AuthenticatedPaymentOrdersRouteImport } from './routes/_authenticated/payment-orders'
import { Route as AuthenticatedMarketIntelligenceRouteImport } from './routes/_authenticated/market-intelligence'
import { Route as AuthenticatedInventoryRouteImport } from './routes/_authenticated/inventory'
import { Route as AuthenticatedHeldByPersonRouteImport } from './routes/_authenticated/held-by-person'
import { Route as AuthenticatedExpensesRouteImport } from './routes/_authenticated/expenses'
import { Route as AuthenticatedDepositsRouteImport } from './routes/_authenticated/deposits'
import { Route as AuthenticatedDealsRouteImport } from './routes/_authenticated/deals'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDailyClosingRouteImport } from './routes/_authenticated/daily-closing'
import { Route as AuthenticatedCustomersRouteImport } from './routes/_authenticated/customers'
import { Route as AuthenticatedCommandCenterRouteImport } from './routes/_authenticated/command-center'
import { Route as AuthenticatedBuyRouteImport } from './routes/_authenticated/buy'
import { Route as AuthenticatedAuditRouteImport } from './routes/_authenticated/audit'
import { Route as AuthenticatedAliInvestorRouteImport } from './routes/_authenticated/ali-investor'
import { Route as AuthenticatedAiBrainRouteImport } from './routes/_authenticated/ai-brain'
import { Route as AuthenticatedAccountsRouteImport } from './routes/_authenticated/accounts'
import { Route as AuthenticatedTradesIndexRouteImport } from './routes/_authenticated/trades.index'
import { Route as AuthenticatedDepositsIndexRouteImport } from './routes/_authenticated/deposits.index'
import { Route as AuthenticatedCustomersIndexRouteImport } from './routes/_authenticated/customers.index'
import { Route as AuthenticatedBroughtInIndexRouteImport } from './routes/_authenticated/brought-in.index'
import { Route as AuthenticatedAccountsIndexRouteImport } from './routes/_authenticated/accounts.index'
import { Route as AuthenticatedTradesIdRouteImport } from './routes/_authenticated/trades.$id'
import { Route as AuthenticatedSellsIdRouteImport } from './routes/_authenticated/sells.$id'
import { Route as AuthenticatedDepositsNewRouteImport } from './routes/_authenticated/deposits.new'
import { Route as AuthenticatedCustomersIdRouteImport } from './routes/_authenticated/customers.$id'
import { Route as AuthenticatedBroughtInNewRouteImport } from './routes/_authenticated/brought-in.new'
import { Route as AuthenticatedAccountsNewRouteImport } from './routes/_authenticated/accounts.new'
import { Route as ApiPublicHooksFetchMarketRatesRouteImport } from './routes/api/public/hooks/fetch-market-rates'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWalletsRoute = AuthenticatedWalletsRouteImport.update({
  id: '/wallets',
  path: '/wallets',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTrustRoute = AuthenticatedTrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTransfersRoute = AuthenticatedTransfersRouteImport.update({
  id: '/transfers',
  path: '/transfers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTradesRoute = AuthenticatedTradesRouteImport.update({
  id: '/trades',
  path: '/trades',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStatementsRoute = AuthenticatedStatementsRouteImport.update({
  id: '/statements',
  path: '/statements',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSellRoute = AuthenticatedSellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRolesRoute = AuthenticatedRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQuickSellRoute = AuthenticatedQuickSellRouteImport.update({
  id: '/quick-sell',
  path: '/quick-sell',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPendingSettlementsRoute =
  AuthenticatedPendingSettlementsRouteImport.update({
    id: '/pending-settlements',
    path: '/pending-settlements',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPaymentOrdersRoute =
  AuthenticatedPaymentOrdersRouteImport.update({
    id: '/payment-orders',
    path: '/payment-orders',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMarketIntelligenceRoute =
  AuthenticatedMarketIntelligenceRouteImport.update({
    id: '/market-intelligence',
    path: '/market-intelligence',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInventoryRoute = AuthenticatedInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHeldByPersonRoute =
  AuthenticatedHeldByPersonRouteImport.update({
    id: '/held-by-person',
    path: '/held-by-person',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExpensesRoute = AuthenticatedExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDepositsRoute = AuthenticatedDepositsRouteImport.update({
  id: '/deposits',
  path: '/deposits',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDealsRoute = AuthenticatedDealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDailyClosingRoute =
  AuthenticatedDailyClosingRouteImport.update({
    id: '/daily-closing',
    path: '/daily-closing',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCustomersRoute = AuthenticatedCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCommandCenterRoute =
  AuthenticatedCommandCenterRouteImport.update({
    id: '/command-center',
    path: '/command-center',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBuyRoute = AuthenticatedBuyRouteImport.update({
  id: '/buy',
  path: '/buy',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditRoute = AuthenticatedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAliInvestorRoute =
  AuthenticatedAliInvestorRouteImport.update({
    id: '/ali-investor',
    path: '/ali-investor',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAiBrainRoute = AuthenticatedAiBrainRouteImport.update({
  id: '/ai-brain',
  path: '/ai-brain',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountsRoute = AuthenticatedAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTradesIndexRoute =
  AuthenticatedTradesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedTradesRoute,
  } as any)
const AuthenticatedDepositsIndexRoute =
  AuthenticatedDepositsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDepositsRoute,
  } as any)
const AuthenticatedCustomersIndexRoute =
  AuthenticatedCustomersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCustomersRoute,
  } as any)
const AuthenticatedBroughtInIndexRoute =
  AuthenticatedBroughtInIndexRouteImport.update({
    id: '/brought-in/',
    path: '/brought-in/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccountsIndexRoute =
  AuthenticatedAccountsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAccountsRoute,
  } as any)
const AuthenticatedTradesIdRoute = AuthenticatedTradesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedTradesRoute,
} as any)
const AuthenticatedSellsIdRoute = AuthenticatedSellsIdRouteImport.update({
  id: '/sells/$id',
  path: '/sells/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDepositsNewRoute =
  AuthenticatedDepositsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedDepositsRoute,
  } as any)
const AuthenticatedCustomersIdRoute =
  AuthenticatedCustomersIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedCustomersRoute,
  } as any)
const AuthenticatedBroughtInNewRoute =
  AuthenticatedBroughtInNewRouteImport.update({
    id: '/brought-in/new',
    path: '/brought-in/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccountsNewRoute =
  AuthenticatedAccountsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedAccountsRoute,
  } as any)
const ApiPublicHooksFetchMarketRatesRoute =
  ApiPublicHooksFetchMarketRatesRouteImport.update({
    id: '/api/public/hooks/fetch-market-rates',
    path: '/api/public/hooks/fetch-market-rates',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/accounts': typeof AuthenticatedAccountsRouteWithChildren
  '/ai-brain': typeof AuthenticatedAiBrainRoute
  '/ali-investor': typeof AuthenticatedAliInvestorRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/buy': typeof AuthenticatedBuyRoute
  '/command-center': typeof AuthenticatedCommandCenterRoute
  '/customers': typeof AuthenticatedCustomersRouteWithChildren
  '/daily-closing': typeof AuthenticatedDailyClosingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/deals': typeof AuthenticatedDealsRoute
  '/deposits': typeof AuthenticatedDepositsRouteWithChildren
  '/expenses': typeof AuthenticatedExpensesRoute
  '/held-by-person': typeof AuthenticatedHeldByPersonRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/market-intelligence': typeof AuthenticatedMarketIntelligenceRoute
  '/payment-orders': typeof AuthenticatedPaymentOrdersRoute
  '/pending-settlements': typeof AuthenticatedPendingSettlementsRoute
  '/quick-sell': typeof AuthenticatedQuickSellRoute
  '/roles': typeof AuthenticatedRolesRoute
  '/sell': typeof AuthenticatedSellRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/statements': typeof AuthenticatedStatementsRoute
  '/trades': typeof AuthenticatedTradesRouteWithChildren
  '/transfers': typeof AuthenticatedTransfersRoute
  '/trust': typeof AuthenticatedTrustRoute
  '/wallets': typeof AuthenticatedWalletsRoute
  '/accounts/new': typeof AuthenticatedAccountsNewRoute
  '/brought-in/new': typeof AuthenticatedBroughtInNewRoute
  '/customers/$id': typeof AuthenticatedCustomersIdRoute
  '/deposits/new': typeof AuthenticatedDepositsNewRoute
  '/sells/$id': typeof AuthenticatedSellsIdRoute
  '/trades/$id': typeof AuthenticatedTradesIdRoute
  '/accounts/': typeof AuthenticatedAccountsIndexRoute
  '/brought-in/': typeof AuthenticatedBroughtInIndexRoute
  '/customers/': typeof AuthenticatedCustomersIndexRoute
  '/deposits/': typeof AuthenticatedDepositsIndexRoute
  '/trades/': typeof AuthenticatedTradesIndexRoute
  '/api/public/hooks/fetch-market-rates': typeof ApiPublicHooksFetchMarketRatesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/ai-brain': typeof AuthenticatedAiBrainRoute
  '/ali-investor': typeof AuthenticatedAliInvestorRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/buy': typeof AuthenticatedBuyRoute
  '/command-center': typeof AuthenticatedCommandCenterRoute
  '/daily-closing': typeof AuthenticatedDailyClosingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/deals': typeof AuthenticatedDealsRoute
  '/expenses': typeof AuthenticatedExpensesRoute
  '/held-by-person': typeof AuthenticatedHeldByPersonRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/market-intelligence': typeof AuthenticatedMarketIntelligenceRoute
  '/payment-orders': typeof AuthenticatedPaymentOrdersRoute
  '/pending-settlements': typeof AuthenticatedPendingSettlementsRoute
  '/quick-sell': typeof AuthenticatedQuickSellRoute
  '/roles': typeof AuthenticatedRolesRoute
  '/sell': typeof AuthenticatedSellRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/statements': typeof AuthenticatedStatementsRoute
  '/transfers': typeof AuthenticatedTransfersRoute
  '/trust': typeof AuthenticatedTrustRoute
  '/wallets': typeof AuthenticatedWalletsRoute
  '/accounts/new': typeof AuthenticatedAccountsNewRoute
  '/brought-in/new': typeof AuthenticatedBroughtInNewRoute
  '/customers/$id': typeof AuthenticatedCustomersIdRoute
  '/deposits/new': typeof AuthenticatedDepositsNewRoute
  '/sells/$id': typeof AuthenticatedSellsIdRoute
  '/trades/$id': typeof AuthenticatedTradesIdRoute
  '/accounts': typeof AuthenticatedAccountsIndexRoute
  '/brought-in': typeof AuthenticatedBroughtInIndexRoute
  '/customers': typeof AuthenticatedCustomersIndexRoute
  '/deposits': typeof AuthenticatedDepositsIndexRoute
  '/trades': typeof AuthenticatedTradesIndexRoute
  '/api/public/hooks/fetch-market-rates': typeof ApiPublicHooksFetchMarketRatesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/accounts': typeof AuthenticatedAccountsRouteWithChildren
  '/_authenticated/ai-brain': typeof AuthenticatedAiBrainRoute
  '/_authenticated/ali-investor': typeof AuthenticatedAliInvestorRoute
  '/_authenticated/audit': typeof AuthenticatedAuditRoute
  '/_authenticated/buy': typeof AuthenticatedBuyRoute
  '/_authenticated/command-center': typeof AuthenticatedCommandCenterRoute
  '/_authenticated/customers': typeof AuthenticatedCustomersRouteWithChildren
  '/_authenticated/daily-closing': typeof AuthenticatedDailyClosingRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/deals': typeof AuthenticatedDealsRoute
  '/_authenticated/deposits': typeof AuthenticatedDepositsRouteWithChildren
  '/_authenticated/expenses': typeof AuthenticatedExpensesRoute
  '/_authenticated/held-by-person': typeof AuthenticatedHeldByPersonRoute
  '/_authenticated/inventory': typeof AuthenticatedInventoryRoute
  '/_authenticated/market-intelligence': typeof AuthenticatedMarketIntelligenceRoute
  '/_authenticated/payment-orders': typeof AuthenticatedPaymentOrdersRoute
  '/_authenticated/pending-settlements': typeof AuthenticatedPendingSettlementsRoute
  '/_authenticated/quick-sell': typeof AuthenticatedQuickSellRoute
  '/_authenticated/roles': typeof AuthenticatedRolesRoute
  '/_authenticated/sell': typeof AuthenticatedSellRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/statements': typeof AuthenticatedStatementsRoute
  '/_authenticated/trades': typeof AuthenticatedTradesRouteWithChildren
  '/_authenticated/transfers': typeof AuthenticatedTransfersRoute
  '/_authenticated/trust': typeof AuthenticatedTrustRoute
  '/_authenticated/wallets': typeof AuthenticatedWalletsRoute
  '/_authenticated/accounts/new': typeof AuthenticatedAccountsNewRoute
  '/_authenticated/brought-in/new': typeof AuthenticatedBroughtInNewRoute
  '/_authenticated/customers/$id': typeof AuthenticatedCustomersIdRoute
  '/_authenticated/deposits/new': typeof AuthenticatedDepositsNewRoute
  '/_authenticated/sells/$id': typeof AuthenticatedSellsIdRoute
  '/_authenticated/trades/$id': typeof AuthenticatedTradesIdRoute
  '/_authenticated/accounts/': typeof AuthenticatedAccountsIndexRoute
  '/_authenticated/brought-in/': typeof AuthenticatedBroughtInIndexRoute
  '/_authenticated/customers/': typeof AuthenticatedCustomersIndexRoute
  '/_authenticated/deposits/': typeof AuthenticatedDepositsIndexRoute
  '/_authenticated/trades/': typeof AuthenticatedTradesIndexRoute
  '/api/public/hooks/fetch-market-rates': typeof ApiPublicHooksFetchMarketRatesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/accounts'
    | '/ai-brain'
    | '/ali-investor'
    | '/audit'
    | '/buy'
    | '/command-center'
    | '/customers'
    | '/daily-closing'
    | '/dashboard'
    | '/deals'
    | '/deposits'
    | '/expenses'
    | '/held-by-person'
    | '/inventory'
    | '/market-intelligence'
    | '/payment-orders'
    | '/pending-settlements'
    | '/quick-sell'
    | '/roles'
    | '/sell'
    | '/settings'
    | '/statements'
    | '/trades'
    | '/transfers'
    | '/trust'
    | '/wallets'
    | '/accounts/new'
    | '/brought-in/new'
    | '/customers/$id'
    | '/deposits/new'
    | '/sells/$id'
    | '/trades/$id'
    | '/accounts/'
    | '/brought-in/'
    | '/customers/'
    | '/deposits/'
    | '/trades/'
    | '/api/public/hooks/fetch-market-rates'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/ai-brain'
    | '/ali-investor'
    | '/audit'
    | '/buy'
    | '/command-center'
    | '/daily-closing'
    | '/dashboard'
    | '/deals'
    | '/expenses'
    | '/held-by-person'
    | '/inventory'
    | '/market-intelligence'
    | '/payment-orders'
    | '/pending-settlements'
    | '/quick-sell'
    | '/roles'
    | '/sell'
    | '/settings'
    | '/statements'
    | '/transfers'
    | '/trust'
    | '/wallets'
    | '/accounts/new'
    | '/brought-in/new'
    | '/customers/$id'
    | '/deposits/new'
    | '/sells/$id'
    | '/trades/$id'
    | '/accounts'
    | '/brought-in'
    | '/customers'
    | '/deposits'
    | '/trades'
    | '/api/public/hooks/fetch-market-rates'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/accounts'
    | '/_authenticated/ai-brain'
    | '/_authenticated/ali-investor'
    | '/_authenticated/audit'
    | '/_authenticated/buy'
    | '/_authenticated/command-center'
    | '/_authenticated/customers'
    | '/_authenticated/daily-closing'
    | '/_authenticated/dashboard'
    | '/_authenticated/deals'
    | '/_authenticated/deposits'
    | '/_authenticated/expenses'
    | '/_authenticated/held-by-person'
    | '/_authenticated/inventory'
    | '/_authenticated/market-intelligence'
    | '/_authenticated/payment-orders'
    | '/_authenticated/pending-settlements'
    | '/_authenticated/quick-sell'
    | '/_authenticated/roles'
    | '/_authenticated/sell'
    | '/_authenticated/settings'
    | '/_authenticated/statements'
    | '/_authenticated/trades'
    | '/_authenticated/transfers'
    | '/_authenticated/trust'
    | '/_authenticated/wallets'
    | '/_authenticated/accounts/new'
    | '/_authenticated/brought-in/new'
    | '/_authenticated/customers/$id'
    | '/_authenticated/deposits/new'
    | '/_authenticated/sells/$id'
    | '/_authenticated/trades/$id'
    | '/_authenticated/accounts/'
    | '/_authenticated/brought-in/'
    | '/_authenticated/customers/'
    | '/_authenticated/deposits/'
    | '/_authenticated/trades/'
    | '/api/public/hooks/fetch-market-rates'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicHooksFetchMarketRatesRoute: typeof ApiPublicHooksFetchMarketRatesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/wallets': {
      id: '/_authenticated/wallets'
      path: '/wallets'
      fullPath: '/wallets'
      preLoaderRoute: typeof AuthenticatedWalletsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/trust': {
      id: '/_authenticated/trust'
      path: '/trust'
      fullPath: '/trust'
      preLoaderRoute: typeof AuthenticatedTrustRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transfers': {
      id: '/_authenticated/transfers'
      path: '/transfers'
      fullPath: '/transfers'
      preLoaderRoute: typeof AuthenticatedTransfersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/trades': {
      id: '/_authenticated/trades'
      path: '/trades'
      fullPath: '/trades'
      preLoaderRoute: typeof AuthenticatedTradesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/statements': {
      id: '/_authenticated/statements'
      path: '/statements'
      fullPath: '/statements'
      preLoaderRoute: typeof AuthenticatedStatementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sell': {
      id: '/_authenticated/sell'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof AuthenticatedSellRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/roles': {
      id: '/_authenticated/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof AuthenticatedRolesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quick-sell': {
      id: '/_authenticated/quick-sell'
      path: '/quick-sell'
      fullPath: '/quick-sell'
      preLoaderRoute: typeof AuthenticatedQuickSellRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pending-settlements': {
      id: '/_authenticated/pending-settlements'
      path: '/pending-settlements'
      fullPath: '/pending-settlements'
      preLoaderRoute: typeof AuthenticatedPendingSettlementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payment-orders': {
      id: '/_authenticated/payment-orders'
      path: '/payment-orders'
      fullPath: '/payment-orders'
      preLoaderRoute: typeof AuthenticatedPaymentOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/market-intelligence': {
      id: '/_authenticated/market-intelligence'
      path: '/market-intelligence'
      fullPath: '/market-intelligence'
      preLoaderRoute: typeof AuthenticatedMarketIntelligenceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory': {
      id: '/_authenticated/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedInventoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/held-by-person': {
      id: '/_authenticated/held-by-person'
      path: '/held-by-person'
      fullPath: '/held-by-person'
      preLoaderRoute: typeof AuthenticatedHeldByPersonRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/expenses': {
      id: '/_authenticated/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AuthenticatedExpensesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/deposits': {
      id: '/_authenticated/deposits'
      path: '/deposits'
      fullPath: '/deposits'
      preLoaderRoute: typeof AuthenticatedDepositsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/deals': {
      id: '/_authenticated/deals'
      path: '/deals'
      fullPath: '/deals'
      preLoaderRoute: typeof AuthenticatedDealsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/daily-closing': {
      id: '/_authenticated/daily-closing'
      path: '/daily-closing'
      fullPath: '/daily-closing'
      preLoaderRoute: typeof AuthenticatedDailyClosingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers': {
      id: '/_authenticated/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedCustomersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/command-center': {
      id: '/_authenticated/command-center'
      path: '/command-center'
      fullPath: '/command-center'
      preLoaderRoute: typeof AuthenticatedCommandCenterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/buy': {
      id: '/_authenticated/buy'
      path: '/buy'
      fullPath: '/buy'
      preLoaderRoute: typeof AuthenticatedBuyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit': {
      id: '/_authenticated/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ali-investor': {
      id: '/_authenticated/ali-investor'
      path: '/ali-investor'
      fullPath: '/ali-investor'
      preLoaderRoute: typeof AuthenticatedAliInvestorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai-brain': {
      id: '/_authenticated/ai-brain'
      path: '/ai-brain'
      fullPath: '/ai-brain'
      preLoaderRoute: typeof AuthenticatedAiBrainRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/accounts': {
      id: '/_authenticated/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AuthenticatedAccountsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/trades/': {
      id: '/_authenticated/trades/'
      path: '/'
      fullPath: '/trades/'
      preLoaderRoute: typeof AuthenticatedTradesIndexRouteImport
      parentRoute: typeof AuthenticatedTradesRoute
    }
    '/_authenticated/deposits/': {
      id: '/_authenticated/deposits/'
      path: '/'
      fullPath: '/deposits/'
      preLoaderRoute: typeof AuthenticatedDepositsIndexRouteImport
      parentRoute: typeof AuthenticatedDepositsRoute
    }
    '/_authenticated/customers/': {
      id: '/_authenticated/customers/'
      path: '/'
      fullPath: '/customers/'
      preLoaderRoute: typeof AuthenticatedCustomersIndexRouteImport
      parentRoute: typeof AuthenticatedCustomersRoute
    }
    '/_authenticated/brought-in/': {
      id: '/_authenticated/brought-in/'
      path: '/brought-in'
      fullPath: '/brought-in/'
      preLoaderRoute: typeof AuthenticatedBroughtInIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/accounts/': {
      id: '/_authenticated/accounts/'
      path: '/'
      fullPath: '/accounts/'
      preLoaderRoute: typeof AuthenticatedAccountsIndexRouteImport
      parentRoute: typeof AuthenticatedAccountsRoute
    }
    '/_authenticated/trades/$id': {
      id: '/_authenticated/trades/$id'
      path: '/$id'
      fullPath: '/trades/$id'
      preLoaderRoute: typeof AuthenticatedTradesIdRouteImport
      parentRoute: typeof AuthenticatedTradesRoute
    }
    '/_authenticated/sells/$id': {
      id: '/_authenticated/sells/$id'
      path: '/sells/$id'
      fullPath: '/sells/$id'
      preLoaderRoute: typeof AuthenticatedSellsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/deposits/new': {
      id: '/_authenticated/deposits/new'
      path: '/new'
      fullPath: '/deposits/new'
      preLoaderRoute: typeof AuthenticatedDepositsNewRouteImport
      parentRoute: typeof AuthenticatedDepositsRoute
    }
    '/_authenticated/customers/$id': {
      id: '/_authenticated/customers/$id'
      path: '/$id'
      fullPath: '/customers/$id'
      preLoaderRoute: typeof AuthenticatedCustomersIdRouteImport
      parentRoute: typeof AuthenticatedCustomersRoute
    }
    '/_authenticated/brought-in/new': {
      id: '/_authenticated/brought-in/new'
      path: '/brought-in/new'
      fullPath: '/brought-in/new'
      preLoaderRoute: typeof AuthenticatedBroughtInNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/accounts/new': {
      id: '/_authenticated/accounts/new'
      path: '/new'
      fullPath: '/accounts/new'
      preLoaderRoute: typeof AuthenticatedAccountsNewRouteImport
      parentRoute: typeof AuthenticatedAccountsRoute
    }
    '/api/public/hooks/fetch-market-rates': {
      id: '/api/public/hooks/fetch-market-rates'
      path: '/api/public/hooks/fetch-market-rates'
      fullPath: '/api/public/hooks/fetch-market-rates'
      preLoaderRoute: typeof ApiPublicHooksFetchMarketRatesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAccountsRouteChildren {
  AuthenticatedAccountsNewRoute: typeof AuthenticatedAccountsNewRoute
  AuthenticatedAccountsIndexRoute: typeof AuthenticatedAccountsIndexRoute
}

const AuthenticatedAccountsRouteChildren: AuthenticatedAccountsRouteChildren = {
  AuthenticatedAccountsNewRoute: AuthenticatedAccountsNewRoute,
  AuthenticatedAccountsIndexRoute: AuthenticatedAccountsIndexRoute,
}

const AuthenticatedAccountsRouteWithChildren =
  AuthenticatedAccountsRoute._addFileChildren(
    AuthenticatedAccountsRouteChildren,
  )

interface AuthenticatedCustomersRouteChildren {
  AuthenticatedCustomersIdRoute: typeof AuthenticatedCustomersIdRoute
  AuthenticatedCustomersIndexRoute: typeof AuthenticatedCustomersIndexRoute
}

const AuthenticatedCustomersRouteChildren: AuthenticatedCustomersRouteChildren =
  {
    AuthenticatedCustomersIdRoute: AuthenticatedCustomersIdRoute,
    AuthenticatedCustomersIndexRoute: AuthenticatedCustomersIndexRoute,
  }

const AuthenticatedCustomersRouteWithChildren =
  AuthenticatedCustomersRoute._addFileChildren(
    AuthenticatedCustomersRouteChildren,
  )

interface AuthenticatedDepositsRouteChildren {
  AuthenticatedDepositsNewRoute: typeof AuthenticatedDepositsNewRoute
  AuthenticatedDepositsIndexRoute: typeof AuthenticatedDepositsIndexRoute
}

const AuthenticatedDepositsRouteChildren: AuthenticatedDepositsRouteChildren = {
  AuthenticatedDepositsNewRoute: AuthenticatedDepositsNewRoute,
  AuthenticatedDepositsIndexRoute: AuthenticatedDepositsIndexRoute,
}

const AuthenticatedDepositsRouteWithChildren =
  AuthenticatedDepositsRoute._addFileChildren(
    AuthenticatedDepositsRouteChildren,
  )

interface AuthenticatedTradesRouteChildren {
  AuthenticatedTradesIdRoute: typeof AuthenticatedTradesIdRoute
  AuthenticatedTradesIndexRoute: typeof AuthenticatedTradesIndexRoute
}

const AuthenticatedTradesRouteChildren: AuthenticatedTradesRouteChildren = {
  AuthenticatedTradesIdRoute: AuthenticatedTradesIdRoute,
  AuthenticatedTradesIndexRoute: AuthenticatedTradesIndexRoute,
}

const AuthenticatedTradesRouteWithChildren =
  AuthenticatedTradesRoute._addFileChildren(AuthenticatedTradesRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountsRoute: typeof AuthenticatedAccountsRouteWithChildren
  AuthenticatedAiBrainRoute: typeof AuthenticatedAiBrainRoute
  AuthenticatedAliInvestorRoute: typeof AuthenticatedAliInvestorRoute
  AuthenticatedAuditRoute: typeof AuthenticatedAuditRoute
  AuthenticatedBuyRoute: typeof AuthenticatedBuyRoute
  AuthenticatedCommandCenterRoute: typeof AuthenticatedCommandCenterRoute
  AuthenticatedCustomersRoute: typeof AuthenticatedCustomersRouteWithChildren
  AuthenticatedDailyClosingRoute: typeof AuthenticatedDailyClosingRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDealsRoute: typeof AuthenticatedDealsRoute
  AuthenticatedDepositsRoute: typeof AuthenticatedDepositsRouteWithChildren
  AuthenticatedExpensesRoute: typeof AuthenticatedExpensesRoute
  AuthenticatedHeldByPersonRoute: typeof AuthenticatedHeldByPersonRoute
  AuthenticatedInventoryRoute: typeof AuthenticatedInventoryRoute
  AuthenticatedMarketIntelligenceRoute: typeof AuthenticatedMarketIntelligenceRoute
  AuthenticatedPaymentOrdersRoute: typeof AuthenticatedPaymentOrdersRoute
  AuthenticatedPendingSettlementsRoute: typeof AuthenticatedPendingSettlementsRoute
  AuthenticatedQuickSellRoute: typeof AuthenticatedQuickSellRoute
  AuthenticatedRolesRoute: typeof AuthenticatedRolesRoute
  AuthenticatedSellRoute: typeof AuthenticatedSellRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStatementsRoute: typeof AuthenticatedStatementsRoute
  AuthenticatedTradesRoute: typeof AuthenticatedTradesRouteWithChildren
  AuthenticatedTransfersRoute: typeof AuthenticatedTransfersRoute
  AuthenticatedTrustRoute: typeof AuthenticatedTrustRoute
  AuthenticatedWalletsRoute: typeof AuthenticatedWalletsRoute
  AuthenticatedBroughtInNewRoute: typeof AuthenticatedBroughtInNewRoute
  AuthenticatedSellsIdRoute: typeof AuthenticatedSellsIdRoute
  AuthenticatedBroughtInIndexRoute: typeof AuthenticatedBroughtInIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountsRoute: AuthenticatedAccountsRouteWithChildren,
  AuthenticatedAiBrainRoute: AuthenticatedAiBrainRoute,
  AuthenticatedAliInvestorRoute: AuthenticatedAliInvestorRoute,
  AuthenticatedAuditRoute: AuthenticatedAuditRoute,
  AuthenticatedBuyRoute: AuthenticatedBuyRoute,
  AuthenticatedCommandCenterRoute: AuthenticatedCommandCenterRoute,
  AuthenticatedCustomersRoute: AuthenticatedCustomersRouteWithChildren,
  AuthenticatedDailyClosingRoute: AuthenticatedDailyClosingRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDealsRoute: AuthenticatedDealsRoute,
  AuthenticatedDepositsRoute: AuthenticatedDepositsRouteWithChildren,
  AuthenticatedExpensesRoute: AuthenticatedExpensesRoute,
  AuthenticatedHeldByPersonRoute: AuthenticatedHeldByPersonRoute,
  AuthenticatedInventoryRoute: AuthenticatedInventoryRoute,
  AuthenticatedMarketIntelligenceRoute: AuthenticatedMarketIntelligenceRoute,
  AuthenticatedPaymentOrdersRoute: AuthenticatedPaymentOrdersRoute,
  AuthenticatedPendingSettlementsRoute: AuthenticatedPendingSettlementsRoute,
  AuthenticatedQuickSellRoute: AuthenticatedQuickSellRoute,
  AuthenticatedRolesRoute: AuthenticatedRolesRoute,
  AuthenticatedSellRoute: AuthenticatedSellRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStatementsRoute: AuthenticatedStatementsRoute,
  AuthenticatedTradesRoute: AuthenticatedTradesRouteWithChildren,
  AuthenticatedTransfersRoute: AuthenticatedTransfersRoute,
  AuthenticatedTrustRoute: AuthenticatedTrustRoute,
  AuthenticatedWalletsRoute: AuthenticatedWalletsRoute,
  AuthenticatedBroughtInNewRoute: AuthenticatedBroughtInNewRoute,
  AuthenticatedSellsIdRoute: AuthenticatedSellsIdRoute,
  AuthenticatedBroughtInIndexRoute: AuthenticatedBroughtInIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicHooksFetchMarketRatesRoute: ApiPublicHooksFetchMarketRatesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
